apiVersion: v1
kind: ConfigMap
metadata:
  name: enqualify-ui
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
    {
      "Application": {
        "Settings": {
          "Production": true,
          "CorsOrigins": [],
          "CSPHeaders": {
            "Enabled": true,
            "DefaultSrc": "",
            "FrameSrc": "blob:",
            "StyleSrc": "'unsafe-inline'",
            "FontSrc": "data:",
            "ImgSrc": "blob: data:",
            "MediaSrc": "localhost:* *.",
            "ScriptSrc": "'unsafe-inline'",
            "ConnectSrc": "localhost:* *:*",
            "FrameAncestors": ""
          },
          "ServiceBase": "{{ .Values.application.settings.ServiceBase }}",
          "ServiceUser": "App",
          "ServiceKey": "app",
          "UIServiceBase": "{{ .Values.application.settings.UIServiceBase }}",
          "CustomerAppServiceActive_": true,
          "MediaServer": false,
          "TimeZoneOffset": 180
        },
        "Features": {
          "Test": false,
          "OpenAPI": false
        },
        "Logging": {
          "RequestLog": {
            "IgnoreHttpCodes": [ 401 ]
          }
        }
      },
      "Logging": {
        "LogLevel": {
          "Default": "Warning",
          "System": "Warning",
          "Microsoft": "Warning",
          "Microsoft.AspNetCore": "Warning",
          "Microsoft.Hosting": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Serilog": {
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "System": "Warning",
            "Microsoft": "Warning",
            "Microsoft.AspNetCore": "Warning",
            "Microsoft.Hosting": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Async",
            "Args": {
              "Configure": [
                {
                  "Name": "Console"
                }
              ]
            }
          },
          {
            "Name": "Async",
            "Args": {
              "Configure": [
                {
                  "Name": "File",
                  "Args": {
                    "path": "../logs/ManagementUI.txt",
                    "rollingInterval": "Day"
                  }
                }
              ]
            }
          }
        ],
        "Properties": {
          "Application": "EnVerify.UI.Management"
        }
      }
    }