apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: enqualify-ui
  name: enqualify-ui
  namespace: {{ .Values.namespace }}
spec:
  ports:
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    io.service: enqualify-ui
